"""add_variant_id_to_cart_items_and_order_items

Revision ID: 029cc9e01d05
Revises: 172b6007934c
Create Date: 2026-05-20 06:04:26.809710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029cc9e01d05'
down_revision: Union[str, Sequence[str], None] = '172b6007934c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('variant_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.add_column('order_items', sa.Column('variant_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'product_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'variant_id')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'variant_id')
    # ### end Alembic commands ###
