"""add customer_addresses table and update order address fields

Revision ID: 07485dd8fed2
Revises: 08bcb9d036c4
Create Date: 2026-05-24 03:40:21.885018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07485dd8fed2'
down_revision: Union[str, Sequence[str], None] = '08bcb9d036c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address_line', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=True)
    op.add_column('order_items', sa.Column('product_description', sa.Text(), nullable=True))
    op.add_column('order_items', sa.Column('product_category', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('product_media', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('product_variant_attributes', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('delivery_status', sa.String(), nullable=True))
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('orders', sa.Column('address_label', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_full_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_phone_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_line', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address_landmark', sa.String(), nullable=True))
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'address_landmark')
    op.drop_column('orders', 'address_postal_code')
    op.drop_column('orders', 'address_country')
    op.drop_column('orders', 'address_state')
    op.drop_column('orders', 'address_city')
    op.drop_column('orders', 'address_line')
    op.drop_column('orders', 'address_phone_number')
    op.drop_column('orders', 'address_full_name')
    op.drop_column('orders', 'address_label')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'delivery_status')
    op.drop_column('order_items', 'product_variant_attributes')
    op.drop_column('order_items', 'product_media')
    op.drop_column('order_items', 'product_category')
    op.drop_column('order_items', 'product_description')
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
