"""add_tool_metadata_to_messages

Revision ID: 08bcb9d036c4
Revises: 029cc9e01d05
Create Date: 2026-05-21 01:37:58.398582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bcb9d036c4'
down_revision: Union[str, Sequence[str], None] = '029cc9e01d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_metadata')
    # ### end Alembic commands ###
