"""remove tracking_number column

Revision ID: 366c51d9078d
Revises: 8906ae192cc1
Create Date: 2026-06-02 04:34:00.950459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366c51d9078d'
down_revision: Union[str, Sequence[str], None] = '8906ae192cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
