"""add_summary_columns_to_conversations

Revision ID: 5ca7b41d369c
Revises: ecafcc00c99b
Create Date: 2026-05-30 01:05:32.348319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca7b41d369c'
down_revision: Union[str, Sequence[str], None] = 'ecafcc00c99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summary_message_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary_message_count')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
