"""add order tracking columns and status history table

Revision ID: 8906ae192cc1
Revises: fe787afa0f6d
Create Date: 2026-06-02 04:24:35.073353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8906ae192cc1'
down_revision: Union[str, Sequence[str], None] = 'fe787afa0f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by_type', sa.String(), nullable=False),
    sa.Column('changed_by_id', sa.String(), nullable=True),
    sa.Column('changed_by_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=True)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'tracking_number')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    # ### end Alembic commands ###
