"""replace media columns with single media json column

Revision ID: 9b1c87a9ce59
Revises: 992908d31ec1
Create Date: 2026-05-20 02:08:11.267082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b1c87a9ce59'
down_revision: Union[str, Sequence[str], None] = '992908d31ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('media', sa.JSON(), nullable=True))
    op.drop_column('products', 'video_urls')
    op.drop_column('products', 'live_video_urls')
    op.drop_column('products', 'live_image_urls')
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('live_image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('live_video_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('video_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'media')
    # ### end Alembic commands ###
